# Generated by Django 4.2 on 2023-04-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateField(verbose_name='start-date'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Credit Leave', 'Credit Leave'), ('Personal Leave', 'Personal Leave'), ('Sick Leave', 'Sick Leave')], max_length=200),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateField(verbose_name='to-date'),
        ),
    ]
