# Generated by Django 4.2 on 2023-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleconnect', '0002_alter_leaverequest_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='to_date',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='No_of_Leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='description',
            field=models.CharField(blank=True, max_length=2054, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
